services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Maps container port 5432 to host port 5432


  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.netdev'
      - '--collector.netstat'
      - '--web.listen-address=0.0.0.0:9100'

  process-exporter:
    image: ncabatoff/process-exporter:latest
    container_name: process-exporter
    restart: unless-stopped
    ports:
      - "9256:9256"
    volumes:
      - ./process-exporter.yml:/etc/process-exporter.yml:ro
      - /proc:/host/proc:ro  # Mount the host's /proc directory
    command:
      - '--config.path=/etc/process-exporter.yml'
      - '--procfs=/host/proc'  # Crucial: Specify the procfs path

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    restart: unless-stopped

  dynamic-routing-client:
    build: ./dynamic-routing
    image: dynamic-routing-client:v0.0.1
    container_name: dynamic-routing-client
    restart: unless-stopped
    ports:
      - "8100:8100"
    volumes:
      - ./dynamic-routing/raw_files:/app/raw_files
    depends_on:
      - db

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Set admin password

volumes:
  prometheus_data:
  grafana_data:

  pgdata:


